export const Emojis: Record<string, string> = {
    Anxious: '😰',
    Apathetic: '😐',
    Tired: '😫',
    Happy: '😊',
    Sad: '😢',
    Angry: '😠',
    Calm: '😌',
    Excited: '🤩',
    ExtremelyCold: '🥶',
    Cold: '😬',
    Pleasant: '😊',
    Hot: '😓',
    ExtremelyHot: '🥵',
    Cloudy: '☁️',
    Rainy: '🌧️',
    YesMenstruation: '🩸',
    PMS: '🍫',
    No: '❌',
    Yes: '✅',
    VeryBad: '😵',
    Bad: '😪',
    Average: '😶',
    Good: '😴',
    VeryGood: '🛌',
    Low: '🍎',
    Normal: '🍽️',
    Large: '🍔'
};